# Data Set
----

In [103]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [234]:
# Presentación 
games =  pd.read_csv('games.csv')
print(games.shape)
games.head()

#Config
pd.set_option('display.max_rows', 10000)



# Transfomraciónes
games["log_Critic_count"] = np.log(games["Critic_Count"])
games["log_Critic_Score"] = np.log(games["Critic_Score"])




# -- NaN -

## Reemplazo con Media ##
reemplazar_con_medias = list(games.iloc[:, -2:].columns.values)
reemplazar_con_medias.append("User_Count")


for i in  reemplazar_con_medias:
    games[f"{i}_is_bad"] = np.where(games[f"{i}"].isna(),1 ,0)
    games[f"{i}"].fillna(value=games[f"{i}"].mean(), inplace=True)
  

## Elimino columnas##
games.drop(columns=["Critic_Count", "Critic_Score", "Rating", "User_Score", "Developer", "Name"], axis=1, inplace=True)

## Elimno Filas ## 
games.dropna( inplace=True)



#Crear Columnas Nuevas
count = games.Publisher.value_counts()
small = count[count<=50]
medium  =  count[(50<count) & (count<=132)]
big =  count[(132<count) & (count<=300)]


games["Small_Publisher"] = np.where(games["Publisher"].isin(small.index.values),1, 0 )
games["Medium_Publisher"] = np.where(games["Publisher"].isin(medium.index.values),1, 0 )
games["Big_Publisher"] = np.where(games["Publisher"].isin(big.index.values),1, 0 )





# Elimino Variables Object 
games.drop("Publisher", axis=1 , inplace=True)

games.to_csv("games_clean.csv", index=False)

(16719, 16)

In [230]:
pd.read_csv("games_clean.csv")

,Platform,Year_of_Release,Genre,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,User_Count,log_Critic_count,log_Critic_Score,log_Critic_count_is_bad,log_Critic_Score_is_bad,User_Count_is_bad,Small_Publisher,Medium_Publisher,Big_Publisher
0,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,82.53,322.000000,3.931826,4.330733,0,0,0,0,0,0
1,NES,1985.0,Platform,29.08,3.58,6.81,0.77,40.24,162.229908,2.999074,4.209473,1,1,1,0,0,0
2,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,35.52,709.000000,4.290459,4.406719,0,0,0,0,0,0
3,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,32.77,192.000000,4.290459,4.382027,0,0,0,0,0,0
4,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,31.37,162.229908,2.999074,4.209473,1,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16413,PS3,2016.0,Action,0.00,0.00,0.01,0.00,0.01,162.229908,2.999074,4.209473,1,1,1,0,0,0
16414,X360,2006.0,Sports,0.00,0.01,0.00,0.00,0.01,162.229908,2.999074,4.209473,1,1,1,0,0,1
16415,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,0.01,162.229908,2.999074,4.209473,1,1,1,0,1,0
16416,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,0.01,162.229908,2.999074,4.209473,1,1,1,1,0,0
16417,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,0.01,162.229908,2.999074,4.209473,1,1,1,0,0,0